name: Rust Formatter
on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.rs'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
    branches:
      - main

jobs:
  rust_format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Run Formatter
        uses: https://git.jonahmakowski.ca/custom_actions/format-rust@1.0.0
        with:
          repo: 'jonahmakowski/box-system'
